## Processed Data From Hive

This is the processed data from Hive

In [ ]:
import pandas as pd

data = pd.read_csv('final_with_headers.csv')
data.head()

C:\Users\Khor Kean Teng\AppData\Local\Temp\ipykernel_8112\2113432523.py:3: DtypeWarning: Columns (0,3,4,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../final_with_headers.csv')

,vendor_id,pickup_time,dropoff_time,flag,rate_code,pu_location,do_location,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
1,2021-07-01 00:30:52,2021-07-01 00:35:36,N,1,74,168,1,1.2,6.0,0.5,0.5,0.00,0.0,1.598015e+09,0.3,7.30,2,1,0.0
2,2021-07-01 00:25:36,2021-07-01 01:01:31,N,1,116,265,2,13.69,42.0,0.5,0.5,0.00,0.0,1.598016e+09,0.3,43.30,2,1,0.0
2,2021-07-01 00:05:58,2021-07-01 00:12:00,N,1,97,33,1,0.95,6.5,0.5,0.5,2.34,0.0,1.598013e+09,0.3,10.14,1,1,0.0
2,2021-07-01 00:41:40,2021-07-01 00:47:23,N,1,74,42,1,1.24,6.5,0.5,0.5,0.00,0.0,1.598015e+09,0.3,7.80,2,1,0.0
2,2021-07-01 00:51:32,2021-07-01 00:58:46,N,1,42,244,1,1.1,7.0,0.5,0.5,0.00,0.0,1.598016e+09,0.3,8.30,2,1,0.0